import { ColorMap, FileFormat } from "types/geojson"

export const GeoJSONEndpoint = "https://5ng8ntubj6.execute-api.ap-south-1.amazonaws.com/cog/info.geojson"
export const TileEndpoint = "https://5ng8ntubj6.execute-api.ap-south-1.amazonaws.com/cog/tiles/WorldMercatorWGS84Quad/{z}/{x}/{y}"

export const colorMaps: ColorMap[] = [
    'accent',
    'accent_r',
    'afmhot',
    'afmhot_r',
    'algae',
    'algae_r',
    'amp',
    'amp_r',
    'autumn',
    'autumn_r',
    'balance',
    'balance_r',
    'binary',
    'binary_r',
    'blues',
    'blues_r',
    'bone',
    'bone_r',
    'brbg',
    'brbg_r',
    'brg',
    'brg_r',
    'bugn',
    'bugn_r',
    'bupu',
    'bupu_r',
    'bwr',
    'bwr_r',
    'cfastie',
    'cividis',
    'cividis_r',
    'cmrmap',
    'cmrmap_r',
    'cool',
    'cool_r',
    'coolwarm',
    'coolwarm_r',
    'copper',
    'copper_r',
    'cubehelix',
    'cubehelix_r',
    'curl',
    'curl_r',
    'dark2',
    'dark2_r',
    'deep',
    'deep_r',
    'delta',
    'delta_r',
    'dense',
    'dense_r',
    'diff',
    'diff_r',
    'flag',
    'flag_r',
    'gist_earth',
    'gist_earth_r',
    'gist_gray',
    'gist_gray_r',
    'gist_heat',
    'gist_heat_r',
    'gist_ncar',
    'gist_ncar_r',
    'gist_rainbow',
    'gist_rainbow_r',
    'gist_stern',
    'gist_stern_r',
    'gist_yarg',
    'gist_yarg_r',
    'gnbu',
    'gnbu_r',
    'gnuplot',
    'gnuplot2',
    'gnuplot2_r',
    'gnuplot_r',
    'gray',
    'gray_r',
    'greens',
    'greens_r',
    'greys',
    'greys_r',
    'haline',
    'haline_r',
    'hot',
    'hot_r',
    'hsv',
    'hsv_r',
    'ice',
    'ice_r',
    'inferno',
    'inferno_r',
    'jet',
    'jet_r',
    'magma',
    'magma_r',
    'matter',
    'matter_r',
    'nipy_spectral',
    'nipy_spectral_r',
    'ocean',
    'ocean_r',
    'oranges',
    'oranges_r',
    'orrd',
    'orrd_r',
    'oxy',
    'oxy_r',
    'paired',
    'paired_r',
    'pastel1',
    'pastel1_r',
]

export const fileFormats: FileFormat[] = [
    'png',
    'npy',
    'tif',
    'jpeg',
    'jpg',
    'jp2',
    'webp',
    'pngraw'
];


export const citiesData = [
    {
      name: "New Delhi",
      code: "IN:DEL",
      proj4def: "+proj=longlat +datum=WGS84 +no_defs",
      bbox: [77.0369, 28.6139, 77.3616, 28.859], // Example bounding box for New Delhi
    },
    {
      name: "Mumbai",
      code: "IN:MUM",
      proj4def: "+proj=longlat +datum=WGS84 +no_defs",
      bbox: [72.7397, 18.9282, 72.9447, 19.307], // Example bounding box for Mumbai
    },
    {
      name: "Bangalore",
      code: "IN:BLR",
      proj4def: "+proj=longlat +datum=WGS84 +no_defs",
      bbox: [77.5043, 12.9, 77.69, 13.2015], // Example bounding box for Bangalore
    },
    {
      name: "Chennai",
      code: "IN:CHE",
      proj4def: "+proj=longlat +datum=WGS84 +no_defs",
      bbox: [80.1161, 13.0475, 80.287, 13.302], // Example bounding box for Chennai
    },
    {
      name: "India",
      code: "IN",
      proj4def: "+proj=longlat +datum=WGS84 +no_defs",
      bbox: [68.1766, 6.4627, 97.4026, 35.5175], // Bounding box for all of India
    },
  ];